<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       xmlns:xi="http://www.w3.org/2001/XInclude"
       xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
       xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
       xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
       xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
       xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics">

	  <xacro:property name="M_PI" value="3.1415926535897931" />
	  <xacro:property name="door_width" value="0.70" />
    <xacro:property name="door_height" value="2.43" />
    <xacro:property name="door_thickness" value="0.05" />
    <xacro:property name="handle_height" value="0.85" />
    <xacro:property name="handle_length" value="0.14" />
    <xacro:property name="x_loc" value="0.0" />
    <xacro:property name="y_loc" value="0.0" />
    <xacro:property name="rotation" value="0.0" />


    <xacro:macro name="door_model_h" params="name parent x_loc y_loc direction_x direction_y">
    	
        <joint name="${name}_joint" type="continuous">
          
          <origin xyz="${x_loc + door_width/2 * direction_x} ${y_loc + door_width/2 * direction_y} 0" rpy="0 0 0" />
          <axis xyz="0 0 1" />
          <limit lower="${-M_PI}" upper="${M_PI}" effort="1000" velocity="10" />
          <safety_controller soft_lower_limit="${-M_PI+0.1}" soft_upper_limit="${M_PI-0.1}"
           k_position="100.0" k_velocity="10.0" />
          <dynamics damping="100" friction="0.0" />
          <parent link="${parent}"/>
          <child link="${name}_link"/>
        </joint>

      	<link name="${name}_link">
      		<inertial >
      			<mass value="30" />
			      <inertia  ixx="1.0" ixy="0.0"  ixz="0.0"
                      iyy="1.0"  iyz="0.0"
                      izz="3.0" />
    		  </inertial>
    		<visual >
      			<origin xyz="${door_width/2 * direction_x} ${door_width/2 * direction_y} ${door_height/2.0}" rpy="0 0 0" />
      			<geometry name="sholder_roll_mesh_file">
        			<box size="${door_width} ${door_thickness} ${door_height}" />
      			</geometry>
    		</visual>
   			<collision >
      			<origin xyz="${door_width/2 * direction_x} ${door_width/2 * direction_y} ${door_height/2.0}" rpy="0 0 0" />
      			<geometry name="door_collision_geom">
        			<box size="${door_width} ${door_thickness} ${door_height}" />
      			</geometry>
    		</collision>
      	</link>
        <gazebo reference="${name}_link">
          <material>PR2/Grey</material>
          <laserRetro>2000</laserRetro>
          <turnGravityOff>true</turnGravityOff>
          <selfCollide>false</selfCollide>
          <dampingFactor>0.01</dampingFactor>
        </gazebo>
    </xacro:macro>  	


</robot>