footprint: [[-0.21, -0.165], [-0.21, 0.165], [0.21, 0.165], [0.21, -0.165]]
footprint_padding: 0.05

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

#meter_scoring: true

resolution: 0.05

obstacle_range: 2.5
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {sensor_frame: front_laser, data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 2.5, raytrace_range: 3.0}

inflation:
    inscribed_radius: 0.5
    inflation_radius: 1.0
