footprint: [[-0.30, -0.30],[-0.30,0.30],[0.30,0.30],[0.30,-0.30]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 5.0
publish_frequency: 3.0
transform_tolerance: 0.25

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

cost_scaling_factor: 10.0
inflation:
    inflation_radius: 1.0

obstacles_laser:
    observation_sources: laser_scan_front
    laser_scan_front: {
        sensor_frame: lidar_1_link,
        data_type: LaserScan,
        topic: lidar_1/scan_filtered,
        marking: true, clearing: true,
        inf_is_valid: true}

static:
    map_topic: /map
    subscribe_to_updates: true
