global_frame: odom
robot_base_frame: base_link
rolling_window: true
static_map: true

plugins:
    - {name: obstacles_laser, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
