global_frame: map
robot_base_frame: base_link
track_unknown_space: true
static_map: true
rolling_window: false

plugins:
    - {name: static, type: "costmap_2d::StaticLayer"}
    - {name: inflation, type: "costmap_2d::InflationLayer"}
